name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Update Packages
      run: |
        npm update
        
    - name: Get Package Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
  
    - name: Docker Build and Publish
      run: |
        docker build . -t morriswa/task-app-angular:${{ steps.package-version.outputs.current-version}}
        ducker push morriswa/task-app-angular:${{ steps.package-version.outputs.current-version}}
