name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Package Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
  
    - name: Docker Build and Publish
      run: |
        docker build . -t morriswa/task-app-angular:${{ steps.package-version.outputs.current-version}}
        ducker push morriswa/task-app-angular:${{ steps.package-version.outputs.current-version}}
